### ISSUE TITLE
Rev B Issues

### ISSUE THREAD

**Issue by brghena** [lab11/buckler#2]
- [x] Add silkscreen label for switch position high/low
- [x] Put IC part numbers on the silkscreen

**Comment by brghena** [comment]
- [ ] Got the RX and TX pins reversed on the Kobuki connection (sigh). Totally fixable in hardware, but we should change it for future revisions.
- [x] Label SD_DETECT test point

**Comment by brghena** [comment]
- [x] 3v3 label is confusing since Vcc is actually less than 3 volts...
- [x] Use some labeling to show hole connection to the signals

**Comment by adkinsjd** [comment]
- [x] Move the gyro/accel axis label out from under the screen

**Comment by nealjack** [comment]
I just committed a fix for most of these issues. I'm not sure what "Use some labeling to show hole connection to the signals" means. Does that mean have silk lines connecting the parallel holes on the side of the board?

**Comment by brghena** [comment]
It wasn't clear to some students that the holes were the same thing as the soldered pins. Probably safe to ignore. Alternatively a silkscreen line from the hole to the pin might be good if you think it's warranted.
